// <auto-generated />
using System;
using IOCX.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IOCX.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810001138_AddEvidenceTable")]
    partial class AddEvidenceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("IOCX.Domain.Entities.EnrichmentCacheEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IocId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IocId");

                    b.HasIndex("ProviderName", "IocId")
                        .IsUnique();

                    b.ToTable("EnrichmentCacheEntries");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.EvidenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScoreContribution")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.ToTable("Evidence");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.InvestigationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IocId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IocId");

                    b.ToTable("Investigations");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.IocEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastInvestigatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedValue")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Iocs");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.ProviderObservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.RelationshipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceIocId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetIocId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceIocId");

                    b.HasIndex("TargetIocId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.EnrichmentCacheEntryEntity", b =>
                {
                    b.HasOne("IOCX.Domain.Entities.IocEntity", "Ioc")
                        .WithMany()
                        .HasForeignKey("IocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ioc");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.EvidenceEntity", b =>
                {
                    b.HasOne("IOCX.Domain.Entities.InvestigationEntity", "Investigation")
                        .WithMany()
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.InvestigationEntity", b =>
                {
                    b.HasOne("IOCX.Domain.Entities.IocEntity", "Ioc")
                        .WithMany("Investigations")
                        .HasForeignKey("IocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ioc");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.ProviderObservationEntity", b =>
                {
                    b.HasOne("IOCX.Domain.Entities.InvestigationEntity", "Investigation")
                        .WithMany("Observations")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigation");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.RelationshipEntity", b =>
                {
                    b.HasOne("IOCX.Domain.Entities.IocEntity", "SourceIoc")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceIocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IOCX.Domain.Entities.IocEntity", "TargetIoc")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetIocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceIoc");

                    b.Navigation("TargetIoc");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.InvestigationEntity", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("IOCX.Domain.Entities.IocEntity", b =>
                {
                    b.Navigation("Investigations");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
